[workspace]
members = [
  "modules/products",
  "modules/users",
  "modules/customers",
  "shared/http",
  "shared/migration",
  "shared/database", 
  "shared/errors",
  "shared/middlewares",
  "config"
]
